vcom test_bench_and_memory/TB_TOP_DLX.vhd

vsim -t 10ps work.DLX_TestBench
log -r *

add wave -position insertpoint sim:/DLX_TestBench/CLK

add wave -position insertpoint sim:/DLX_TestBench/DDLX/DECODEhw/op_code sim:/DLX_TestBench/DDLX/DECODEhw/ADD_RS1 sim:/DLX_TestBench/DDLX/DECODEhw/ADD_RS2 sim:/DLX_TestBench/DDLX/DECODEhw/ADD_WS1

add wave -divider
add wave -position insertpoint sim:/DLX_TestBench/DDLX/DataPath/RF/DATAIN
add wave -position insertpoint sim:/DLX_TestBench/DDLX/DataPath/RF/ADD_WR

add wave -position insertpoint -group PROC_REGS -label R0 sim:/DLX_TestBench/DDLX/DataPath/RF/REGS(0)/GLOB_BLK/BLOCK_GLOB/Q
add wave -position insertpoint -group PROC_REGS -label R1 sim:/DLX_TestBench/DDLX/DataPath/RF/REGS(1)/GLOB_BLK/BLOCK_GLOB/Q
add wave -position insertpoint -group PROC_REGS -label R2 sim:/DLX_TestBench/DDLX/DataPath/RF/REGS(2)/GLOB_BLK/BLOCK_GLOB/Q
add wave -position insertpoint -group PROC_REGS -label R3 sim:/DLX_TestBench/DDLX/DataPath/RF/REGS(3)/GLOB_BLK/BLOCK_GLOB/Q
add wave -position insertpoint -group PROC_REGS -label R4 sim:/DLX_TestBench/DDLX/DataPath/RF/REGS(4)/GLOB_BLK/BLOCK_GLOB/Q
add wave -position insertpoint -group PROC_REGS -label R5 sim:/DLX_TestBench/DDLX/DataPath/RF/REGS(5)/GLOB_BLK/BLOCK_GLOB/Q
add wave -position insertpoint -group PROC_REGS -label R6 sim:/DLX_TestBench/DDLX/DataPath/RF/REGS(6)/GLOB_BLK/BLOCK_GLOB/Q
add wave -position insertpoint -group PROC_REGS -label R7 sim:/DLX_TestBench/DDLX/DataPath/RF/REGS(7)/GLOB_BLK/BLOCK_GLOB/Q

add wave -position insertpoint -group PROC_REGS -label R8 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[31:0]
add wave -position insertpoint -group PROC_REGS -label R9 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[63:32]
add wave -position insertpoint -group PROC_REGS -label R10 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[95:64]
add wave -position insertpoint -group PROC_REGS -label R11 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[127:96]
add wave -position insertpoint -group PROC_REGS -label R12 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[159:128]
add wave -position insertpoint -group PROC_REGS -label R13 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[191:160]
add wave -position insertpoint -group PROC_REGS -label R14 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[223:192]
add wave -position insertpoint -group PROC_REGS -label R15 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[255:224]
add wave -position insertpoint -group PROC_REGS -label R16 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[287:256]
add wave -position insertpoint -group PROC_REGS -label R17 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[319:288]
add wave -position insertpoint -group PROC_REGS -label R18 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[351:320]
add wave -position insertpoint -group PROC_REGS -label R19 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[383:352]
add wave -position insertpoint -group PROC_REGS -label R20 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[415:384]
add wave -position insertpoint -group PROC_REGS -label R21 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[447:416]
add wave -position insertpoint -group PROC_REGS -label R22 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[479:448]
add wave -position insertpoint -group PROC_REGS -label R23 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[511:480]
add wave -position insertpoint -group PROC_REGS -label R24 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[543:512]
add wave -position insertpoint -group PROC_REGS -label R25 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[575:544]
add wave -position insertpoint -group PROC_REGS -label R26 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[607:576]
add wave -position insertpoint -group PROC_REGS -label R27 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[639:608]
add wave -position insertpoint -group PROC_REGS -label R28 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[671:640]
add wave -position insertpoint -group PROC_REGS -label R29 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[703:672]
add wave -position insertpoint -group PROC_REGS -label R30 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[735:704]
add wave -position insertpoint -group PROC_REGS -label R31 sim:/DLX_TestBench/DDLX/DataPath/RF/SEL_BLK/curr_proc_regs[767:736]
